
- name: Get Homebrew zsh
  shell: "echo $(brew --prefix)/bin/zsh"
  register: homebrew_zsh

- name: Enable hombrews zsh as default shell
  sudo: yes
  lineinfile: dest=/etc/shells line={{ homebrew_zsh }}

- name: Set hombrews zsh as default shell
  sudo: yes
  user: name=farfanoide shell={{ homebrew_zsh }}
