- name: Show the main window when launching Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=OpenMainWindow type=bool value=true state=present

- name: Visualize CPU usage in the Activity Monitor Dock icon
  osx_defaults: domain=com.apple.ActivityMonitor key=IconType type=int value=5 state=present

- name: Show all processes in Activity Monitor
  osx_defaults: domain=com.apple.ActivityMonitor key=ShowCategory type=int value=0 state=present

- name: Sort Activity Monitor results by CPU usage
  osx_defaults: domain=com.apple.ActivityMonitor key=SortColumn type=string value="CPUUsage" state=present

- name: Sort Activity Monitor results ordered DESC
  osx_defaults: domain=com.apple.ActivityMonitor key=SortDirection type=int value=0 state=present

- name: Use plain text mode for new TextEdit documents
  osx_defaults: domain=com.apple.TextEdit key=RichText type=int value=0 state=present

- name: Open files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncoding type=int value=4 state=present

- name: Save files as UTF-8 in TextEdit
  osx_defaults: domain=com.apple.TextEdit key=PlainTextEncodingForWrite type=int value=4 state=present
