- name: Home folder as the default location for new Finder windows
  osx_defaults: domain=com.apple.finder key=NewWindowTarget type=string value="PfLo" state=present

- name: Set Home folder as the default location for new Finder windows
  osx_defaults: domain=com.apple.finder key=NewWindowTargetPath type=string value="file://${HOME}/" state=present

- name: Show icons for external hard drives on the desktop
  osx_defaults: domain=com.apple.finder key=ShowExternalHardDrivesOnDesktop type=bool value=true state=present

- name: Show icons for hard drives on the desktop
  osx_defaults: domain=com.apple.finder key=ShowHardDrivesOnDesktop type=bool value=true state=present

- name: Show icons for servers on the desktop
  osx_defaults: domain=com.apple.finder key=ShowMountedServersOnDesktop type=bool value=true state=present

- name: Show icons for removable media on the desktop
  osx_defaults: domain=com.apple.finder key=ShowRemovableMediaOnDesktop type=bool value=true state=present

- name: Show status bar
  osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true state=present

- name: Show path bar
  osx_defaults: domain=com.apple.finder key=ShowPathbar type=bool value=true state=present

- name: Finder allow text selection in Quick Look
  osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true state=present

  # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
- name: Use list view in all Finder windows by default
  osx_defaults: domain=com.apple.finder key=FXPreferredViewStyle type=string value="Nlsv" state=present

- name: Disable the warning before emptying the Trash
  osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=false state=present

# - name: Empty Trash securely by default
#   osx_defaults: domain=com.apple.finder key=EmptyTrashSecurely type=bool value=true state=present

- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  osx_defaults: domain=com.apple.NetworkBrowser key=BrowseAllInterfaces type=bool value=true state=present

 # Reference -> 1 => small, 2 => medium, 3 => large
- name: Set sidebar icon size to small
  osx_defaults: domain=NSGlobalDomain key=NSTableViewDefaultSizeMode type=int value=1 state=present

