
- name: Set a blazingly fast keyboard repeat rate
  osx_defaults: domain=NSGlobalDomain key=KeyRepeat type=int value=0 state=present

- name: Disable press-and-hold for keys in favor of key repeat
  osx_defaults: domain=NSGlobalDomain key=ApplePressAndHoldEnabled type=bool value=false state=present

- name: Enable full keyboard access for all controls (Tab navigation)
  osx_defaults: domain=NSGlobalDomain key=AppleKeyboardUIMode type=int value=3 state=present

- name: Disable auto-correct
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticSpellingCorrectionEnabled type=bool value=false state=present
